import { catalog, Category, Product } from "./catalog";
export type Intent={ raw:string; category?:Category; minBudget?:number; maxBudget?:number; requirements:{ram?:string;portability?:"high"}; preferences?:string[]; sortPreference?:"value"|"rating"|"portability"; useCase?:string; setup?:boolean; confidence?:number; clarificationNeeded?:boolean };
export type Recommendation={product:Product;matchScore:number;reasons:string[];matchedRequirements:string[];tradeoffs:string[]};
const parseBudget=(input:string)=>{const match=input.toLowerCase().match(/(?:under|below|budget(?: of)?|less than)\s*(?:₹|rs\.?\s*)?\s*(\d+(?:[,.]\d+)?\s*k?)/); if(!match)return undefined; const n=match[1].replace(/[\s,]/g,""); return n.endsWith("k")?Number(n.slice(0,-1))*1000:Number(n)};
export function parseBuyerRequest(raw:string):Intent { const text=raw.toLowerCase(); let category:Category|undefined; if(/gaming setup|build.*setup/.test(text)) category="gaming-laptop"; else if(/gaming laptop/.test(text))category="gaming-laptop"; else if(/laptop/.test(text))category="laptop"; else if(/headphone/.test(text))category="headphones"; else if(/keyboard/.test(text))category="keyboard"; else if(/monitor|display/.test(text))category="monitor"; else if(/mouse/.test(text))category="mouse"; const ram=text.match(/(8|16|32|64)\s*gb\s*(?:ram)?/); const useCase=["coding","programming","gaming","college","productivity","travel"].find(x=>text.includes(x)); const portable=/lightweight|portable|light\b/.test(text); return {raw,category,maxBudget:parseBudget(text),requirements:{...(ram?{ram:`${ram[1]}GB`}:{}),...(portable?{portability:"high" as const}:{})},preferences:portable?["portability"]:[],sortPreference:portable?"portability":"value",useCase:useCase==="programming"?"coding":useCase,setup:/setup/.test(text),clarificationNeeded:!category}; }
function recommendation(product:Product,intent:Intent):Recommendation {let score=40;const reasons:string[]=[];const matched:string[]=[];const tradeoffs:string[]=[]; if(intent.maxBudget){const ratio=product.price/intent.maxBudget; if(ratio<=1){score+=22;reasons.push(`Within your ₹${intent.maxBudget.toLocaleString("en-IN")} budget`);matched.push("budget");if(ratio>.85)score+=3}else tradeoffs.push("Close to your stated budget")}; if(intent.requirements?.ram){if(product.specifications.ram===intent.requirements.ram){score+=20;reasons.push(`Meets the ${intent.requirements.ram} RAM requirement`);matched.push("ram")}else tradeoffs.push(`${product.specifications.ram||"Standard"} RAM instead of ${intent.requirements.ram}`)};if(intent.useCase&&product.useCases.includes(intent.useCase)){score+=16;reasons.push(`Strong fit for ${intent.useCase}`);matched.push("use_case")};const ai=intent.useCase==="gaming"?product.aiAttributes.gamingScore:intent.useCase==="coding"?product.aiAttributes.codingScore:product.aiAttributes.valueScore;score+=Math.round((ai||product.aiAttributes.valueScore)*.13);score+=Math.round(product.rating*2);if(product.stock>0){score+=3;reasons.push("Currently in stock");matched.push("stock")};if(!tradeoffs.length&&product.category==="laptop"&&!product.specifications.gpu)tradeoffs.push("No dedicated GPU");return {product,matchScore:Math.min(99,score),reasons,matchedRequirements:matched,tradeoffs};}
export function searchCatalog(intent:Intent){return catalog.filter(p=>!intent.category||p.category===intent.category).filter(p=>p.stock>0).filter(p=>!intent.maxBudget||p.price<=intent.maxBudget).filter(p=>!intent.requirements?.ram||p.specifications.ram===intent.requirements.ram).map(p=>recommendation(p,intent)).sort((a,b)=>b.matchScore-a.matchScore);}
export function getRelatedProducts(product:Product){return product.relatedProductIds.map(id=>catalog.find(p=>p.id===id)).filter((p):p is Product=>Boolean(p&&p.stock>0));}
export function buildOfferPreview(product:Product,extras:Product[]){const subtotal=[product,...extras].reduce((sum,p)=>sum+p.price,0);const discount=extras.length?Math.min(650,Math.round(extras.reduce((s,p)=>s+p.price,0)*.12)):0;return {subtotal,discount,finalAmount:subtotal-discount,items:[product,...extras]};}
