import test from "node:test"; import assert from "node:assert/strict"; import { parseBuyerRequest, searchCatalog, getRelatedProducts, buildOfferPreview } from "./buyer.ts";
test("parses laptop, budget, RAM and coding",()=>{const x=parseBuyerRequest("I need a coding laptop under ₹60,000 with 16GB RAM");assert.equal(x.category,"laptop");assert.equal(x.maxBudget,60000);assert.equal(x.requirements.ram,"16GB");assert.equal(x.useCase,"coding")});
test("parses 60k",()=>assert.equal(parseBuyerRequest("gaming laptop under 60k").maxBudget,60000));
test("parses spaced INR shorthand",()=>assert.equal(parseBuyerRequest("monitor under ₹60 K").maxBudget,60000));
test("parses a RAM requirement independently",()=>assert.equal(parseBuyerRequest("laptop with 16GB RAM").requirements.ram,"16GB"));
test("parses gaming setup intent",()=>assert.equal(parseBuyerRequest("build me a gaming setup under 80000").category,"gaming-laptop"));
test("searches, filters, ranks and excludes stock",()=>{const r=searchCatalog(parseBuyerRequest("coding laptop under 60000 with 16GB RAM"));assert.ok(r.length>0);assert.ok(r.every(x=>x.product.price<=60000&&x.product.stock>0));assert.ok(r[0].matchScore>=r.at(-1).matchScore)});
test("returns related products and calculates offer",()=>{const product=searchCatalog(parseBuyerRequest("coding laptop under 60000 with 16GB RAM"))[0].product;const extras=getRelatedProducts(product);assert.ok(extras.length>0);const offer=buildOfferPreview(product,[extras[0]]);assert.ok(offer.finalAmount<offer.subtotal)});
test("has a no-match scenario",()=>assert.equal(searchCatalog(parseBuyerRequest("laptop under 10000 with 32GB RAM")).length,0));
test("filters out of budget products",()=>assert.ok(searchCatalog(parseBuyerRequest("headphones under 4000")).every(x=>x.product.price<=4000)));
test("filters products with no stock",()=>assert.ok(searchCatalog(parseBuyerRequest("headphones under 5000")).every(x=>x.product.stock>0)));
test("recommendation score is a bounded percentage",()=>{const x=searchCatalog(parseBuyerRequest("coding laptop under 60000 with 16GB RAM"))[0];assert.ok(x.matchScore>=0&&x.matchScore<=100);assert.ok(x.reasons.length>0)});
test("recommendations provide explainable matched requirements",()=>{const x=searchCatalog(parseBuyerRequest("coding laptop under 60000 with 16GB RAM"))[0];assert.ok(x.matchedRequirements.includes("budget"));assert.ok(x.matchedRequirements.includes("ram"))});
